# Generated by Django 4.0.2 on 2022-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_is_online_user_wons_user_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='league',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Grand Master', 'Grand Master')], default='Bronze', max_length=255, verbose_name='league'),
        ),
    ]
