# Generated by Django 4.0.2 on 2022-02-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_current_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
