# Generated by Django 4.0.2 on 2022-02-16 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_game_id', models.CharField(default=None, max_length=10, unique=True, verbose_name='Unique ID')),
                ('concluded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Concluded At')),
                ('game_type', models.CharField(choices=[('public', 'Public'), ('custom', 'Custom')], default='public', max_length=30, verbose_name='Game Type')),
                ('winner_username', models.CharField(max_length=255, verbose_name='Winner Username')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamehistory', verbose_name='Game Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
