# Generated by Django 4.0.2 on 2022-02-16 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_participant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('W', 'Wild'), ('WF', 'Wild Four')], max_length=2, verbose_name='Category')),
                ('number', models.PositiveSmallIntegerField(choices=[(13, 'None'), (0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Skip'), (12, 'Draw Two'), (11, 'Reverse')], verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_game_id', models.CharField(default=None, max_length=10, unique=True, verbose_name='Unique ID')),
                ('is_game_running', models.BooleanField(default=False, verbose_name='Is Game Running')),
                ('players_count', models.IntegerField(default=0, verbose_name='Joined Player Count')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0, verbose_name='Type')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room', verbose_name='Game Room')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
    ]
