# Generated by Django 4.0.2 on 2022-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_card_room_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='New Public Game', max_length=20),
        ),
    ]
